language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison libcurl4-openssl-dev libssl-dev
env:
  - NGINX_SRC_MAJOR=1
    NGINX_SRC_MINOR=4
    NGINX_SRC_PATCH=7
  - NGINX_SRC_MAJOR=1
    NGINX_SRC_MINOR=6
    NGINX_SRC_PATCH=3
  - NGINX_SRC_MAJOR=1
    NGINX_SRC_MINOR=8
    NGINX_SRC_PATCH=0
  - NGINX_SRC_MAJOR=1
    NGINX_SRC_MINOR=9
    NGINX_SRC_PATCH=9

script:
  - echo "NGINX_SRC_MAJOR=${NGINX_SRC_MAJOR}" > nginx_version
  - echo "NGINX_SRC_MINOR=${NGINX_SRC_MINOR}" >> nginx_version
  - echo "NGINX_SRC_PATCH=${NGINX_SRC_PATCH}" >> nginx_version
  - echo "NGINX_SRC_VER=nginx-${NGINX_SRC_MAJOR}.${NGINX_SRC_MINOR}.${NGINX_SRC_PATCH}" >> nginx_version
  - sh test.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#hosting-ja"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "[%{message}] %{repository} (%{commit}) by %{author}: See %{build_url}"
  webhooks:
    - secure: "aGWGYK++jT3o4ENZ4NzkyCHBn1f8eyqXEa7dEph+088qQlnnieqDn3xzlmBA1hiqouZ6ioTICSfYUaXk6h4zte1SX0nR2rO/XJYhseTqaiqgx+1cqw9aWEkwsAYu0oDuND5pMAa2so3zn38UuHLKvOMNEhi/xRXMFx3Bl5P8Pxk="


